# render.yaml (VERSÃO FINAL COM ESTRUTURA CORRETA)

# A chave principal 'resources' define tudo que será criado.
resources:
  # --- 1. O Banco de Dados PostgreSQL ---
  - name: blaze-db
    type: psql
    plan: free

  # --- 2. O Worker em Segundo Plano (Coletor) ---
  - name: coletor-blaze
    type: worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python coletor_blaze.py"
    envVars:
      - key: DATABASE_URL
        fromResource:
          name: blaze-db
          type: psql
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: TELEGRAM_TOKEN_1
        sync: false 
      - key: TELEGRAM_CHAT_ID_1
        sync: false
      - key: TELEGRAM_TOKEN_2
        sync: false
      - key: TELEGRAM_CHAT_ID_2
        sync: false
      - key: TELEGRAM_TOKEN_3
        sync: false
      - key: TELEGRAM_CHAT_ID_3
        sync: false

  # --- 3. O Serviço Web (Painel Flask) ---
  - name: monitor-blaze
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromResource:
          name: blaze-db
          type: psql
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: TELEGRAM_TOKEN_1
        sync: false
      - key: TELEGRAM_CHAT_ID_1
        sync: false
      - key: TELEGRAM_TOKEN_2
        sync: false
      - key: TELEGRAM_CHAT_ID_2
        sync: false
      - key: TELEGRAM_TOKEN_3
        sync: false
      - key: TELEGRAM_CHAT_ID_3
        sync: false