# render.yaml (VERSÃO FINAL E CORRIGIDA)
services:
  # --- 1. O Banco de Dados PostgreSQL ---
  - type: psql
    name: blaze-db
    plan: free

  # --- 2. O Worker em Segundo Plano (Coletor) ---
  - type: worker
    name: coletor-blaze
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python coletor_blaze.py"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: blaze-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: TELEGRAM_TOKEN_1
        sync: false 
      - key: TELEGRAM_CHAT_ID_1
        sync: false
      - key: TELEGRAM_TOKEN_2
        sync: false
      - key: TELEGRAM_CHAT_ID_2
        sync: false
      - key: TELEGRAM_TOKEN_3
        sync: false
      - key: TELEGRAM_CHAT_ID_3
        sync: false

  # --- 3. O Serviço Web (Painel Flask) ---
  - type: web
    name: monitor-blaze
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: blaze-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: TELEGRAM_TOKEN_1
        sync: false
      - key: TELEGRAM_CHAT_ID_1
        sync: false
      - key: TELEGRAM_TOKEN_2
        sync: false
      - key: TELEGRAM_CHAT_ID_2
        sync: false
      - key: TELEGRAM_TOKEN_3
        sync: false
      - key: TELEGRAM_CHAT_ID_3
        sync: false