# Arquivo: render.yaml
# Versão FINAL corrigida

services:
  # Serviço 1: Aplicação Web com Flask (o painel de controle)
  - type: web
    name: bot-dashboard
    env: python
    rootDir: app
    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: blaze-db # Lembre-se de confirmar o nome do seu DB
          property: connectionString
      - key: TELEGRAM_TOKEN_1
        sync: false
      - key: TELEGRAM_CHAT_ID_1
        sync: false
      - key: TELEGRAM_TOKEN_2
        sync: false